stop building with hhvm because it stopped working (#146)
it seems a recent version of hhvm did a BC break, builds that have been successful now fail with
```
Fatal error: Uncaught TypeError: Argument 1 passed to spec\Http\Client\Exception\HttpExceptionSpec::let() must implement interface Psr\Http\Message\RequestInterface, PhpSpec\Wrapper\Collaborator given in /home/travis/build/php-http/httplug/spec/Exception/HttpExceptionSpec.php:14
```